services:
  mongodb:
    hostname: mongodb
    image: akzsato/database
    ports:
      - "27017:27017"
  app:
    hostname: app
    image: akzsato/app
    env_file:
      - ./app/.env
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  redis:
    hostname: redis
    image: akzsato/redis
    ports:
      - "6379:6379"
  webhook:
    hostname: webhook
    image: akzsato/webhook
    env_file:
      - ./webhook-pagamentos/.env
    depends_on:
      - redis