apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongodb
  template:
    metadata:
      labels:
        service: mongodb
    spec:
      containers:
        - image: akzsato/database
          name: mongodb
          ports:
            - containerPort: 27017
              protocol: TCP
      hostname: mongodb
      restartPolicy: Always
