apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis
  template:
    metadata:
      labels:
        service: redis
    spec:
      containers:
        - image: akzsato/redis
          name: redis
          ports:
            - containerPort: 6379
              protocol: TCP
      hostname: redis
      restartPolicy: Always
